In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [92]:
file_loc="winequality_red.csv"
df=pd.read_csv(file_loc)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [72]:
df.shape

(1599, 12)

In [73]:
#check for any empty rows while reading (blank rows)
#dropping null value rows. sometimes occurs while reading a file. these are not not missing values
#optional step
df=df.dropna()
df.reset_index(inplace=True) #to reset indexes after dropping empty rows if present
df

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [93]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [94]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [95]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

**ALL DATA SHOULD BE NUMERIC BEFORE DOING NEXT STEPS. PERFORM NECESSARY ANALYSIS. (in this dataframe, all data is numeric, many dfs have numeric and categorical data)**

**step 1 :Divide data into 2 parts**

In [96]:
x=df.drop("quality",axis=1)
y=df['quality']

#**Divide both data  train and test**
-will use train test split from sklearn model selection
-it takes following parameters.
    --x :ip data
    -- y:op data

In [97]:
#step2
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,random_state=1234,test_size=0.30)

In [98]:
x_train.shape,x_test.shape

((1119, 11), (480, 11))

In [99]:
y_train.shape,y_test.shape

((1119,), (480,))

In [100]:
#step3
#check point1
print("the shape of df is ", df.shape)
print("the shape of x_train is ", x_train.shape)
print("the shape of x_test is ", x_test.shape)
print("the shape of y_train is ", y_train.shape)   #series gives only rows and one column. y has only one column.
# see step 1
print("the shape of x_test is ", y_test.shape)  #series

the shape of df is  (1599, 12)
the shape of x_train is  (1119, 11)
the shape of x_test is  (480, 11)
the shape of y_train is  (1119,)
the shape of x_test is  (480,)

In [101]:
#check point2
#check the observation indexes of both x_train and y_train
x_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
642,9.9,0.540,0.45,2.3,0.071,16.0,40.0,0.99910,3.39,0.62,9.4
678,8.3,0.780,0.10,2.6,0.081,45.0,87.0,0.99830,3.48,0.53,10.0
412,7.1,0.735,0.16,1.9,0.100,15.0,77.0,0.99660,3.27,0.64,9.3
73,8.3,0.675,0.26,2.1,0.084,11.0,43.0,0.99760,3.31,0.53,9.2
985,7.4,0.580,0.00,2.0,0.064,7.0,11.0,0.99562,3.45,0.58,11.3
...,...,...,...,...,...,...,...,...,...,...,...
1228,5.1,0.420,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.6
1077,8.6,0.370,0.65,6.4,0.080,3.0,8.0,0.99817,3.27,0.58,11.0
1318,7.5,0.630,0.27,2.0,0.083,17.0,91.0,0.99616,3.26,0.58,9.8
723,7.1,0.310,0.30,2.2,0.053,36.0,127.0,0.99650,2.94,1.62,9.5
815,10.8,0.450,0.33,2.5,0.099,20.0,38.0,0.99818,3.24,0.71,10.8

In [102]:
y_train

642     5
678     5
412     5
73      4
985     6
       ..
1228    7
1077    5
1318    6
723     5
815     5
Name: quality, Length: 1119, dtype: int64

In [103]:
#check point3
#check the observation indexes of both x_test and y_test
x_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
688,7.7,0.660,0.04,1.6,0.039,4.0,9.0,0.99620,3.40,0.47,9.4
961,7.1,0.560,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3
726,8.1,0.720,0.09,2.8,0.084,18.0,49.0,0.99940,3.43,0.72,11.1
537,8.1,0.825,0.24,2.1,0.084,5.0,13.0,0.99720,3.37,0.77,10.7
1544,8.4,0.370,0.43,2.3,0.063,12.0,19.0,0.99550,3.17,0.81,11.2
...,...,...,...,...,...,...,...,...,...,...,...
1461,6.2,0.785,0.00,2.1,0.060,6.0,13.0,0.99664,3.59,0.61,10.0
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6
1045,6.9,0.440,0.00,1.4,0.070,32.0,38.0,0.99438,3.32,0.58,11.4
1498,6.6,0.895,0.04,2.3,0.068,7.0,13.0,0.99582,3.53,0.58,10.8
42,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5

In [104]:
y_test

688     5
961     5
726     6
537     6
1544    7
       ..
1461    4
1591    6
1045    6
1498    6
42      6
Name: quality, Length: 480, dtype: int64

In [105]:
x_train.ndim

2

In [106]:
#step 4
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [107]:
x_test.iloc[0]   #series
#inorder to pass a test sample to a model ,we need to pass a list of values or an array of values
#or a tuple of values
x_test.iloc[0].values #passing a single value at a atime

array([7.7   , 0.66  , 0.04  , 1.6   , 0.039 , 4.    , 9.    , 0.9962,
       3.4   , 0.47  , 9.4   ])

In [89]:
LR.predict([x_test.iloc[0].values,x_test.iloc[1].values])

array([5.16003375, 5.31953766])

**Batch predictions**
- in the below cells, we are passing all the test data observations at a time, after model development.
**Realtime or Endpoint predictions**
- After model development, we can pass a single observetion from test data. It will give a quick response.
- It is called as Real Time Prediction. (Below  Testing)
- Note
    - No. of values passing in a list = no. of columns
    - no. of columns model is trained with = No of values model considers for testing.
- Refer Vertex AI - get online predictions website

In [108]:
ip1=[1,2,3,4,5,6,7,8,9,10,11]
LR.predict([ip1])

array([-82.48338949])

In [ ]:
x_test.shape,y_test.shape,y_predictions.shape

In [ ]:
test_data=x_test
test_data['y_actual']=y_test
test_data['y_predictions']=y_predictions
test_data

- For easy understanding of y_actual (y_test) and y_predictions,
- we can create a dataframe with those columns
- y_test is series
- y_predictions is numpy array values.

In [ ]:
print(y_test.values[:5])
print(y_predictions[:5])

In [ ]:
#step5
#Model predictions on x_test
y_predictions=LR.predict(x_test.iloc[0].values,x_test.iloc[1].values)
y_predictions

In [ ]:
#step 6 Model Evaluation
#comparing predictions with y_test data ie., y_actual data
#RMSE
#MSE
#MAE
#R-square
from sklearn.metrics import r2_score,mean_squared_error
R2=r2_score(y_test,y_predictions)
MSE=mean_squared_error(y_test,y_predictions)
#MSE**(1/2)
RMSE=np.sqrt(MSE)
#accuracy_score(y_test,y_predictions) # it is a regression tech
print("R-sqaure:",R2)
print("MSE:",MSE)
print("RMSE:",RMSE)

**Finding MSE using python using formulae**

- steps:
    - As we have y_test and y_predictions, Using for loop, we substract each y_test value w.r.t y_predictions
    - Then Square the each substractions 
    - Then using a sum variable, add each squared value to finally get sum of all squared values.
    - Divide the sum by len(y_test) or len(y_predictions)

In [ ]:
s=0
for i in range(len(y_test)):  #len of y_test or y_predictions will be same. we can use any of the lengths
    v1=(y_test.values[i]-y_predictions[i])  #y_test is a column
    v1=v1**2
    s=s+v1
MSE=(s/len(y_test))
MSE

In [ ]:
RMSE=MSE**0.5
RMSE

In [ ]:
#Delloite company QUE
v1=[(1,2),(3,5),(5,7)]
v2=(10.20)
#calculate the distance b/w each poit ain v1 w.r.t v2

**Feature Selection**
- 1) Dropping the constant features (Regression and Classification
- 2) Information gain(Classification)
- 3) p-value (Regression)
- 4) VIF (Regression)
- 5) Forward selection and backward selection (Regression and classification)
- 6) Correlation with target column (Regression and classification)

**Feature Selection Methods**
- **using Regression problems (Method-1)**
- p_value concept
- H_o : There is no r/n b/w Independent and dependent variable
- H_a : There is a r/n b/w Independent and dependent variable
    - If p>alpha : Evidence is low for H_o, Not Reject the Null Hypothesis  (read Notes)
 
- sklearn package don't have the option to calculate p_value. 
- In stats model, we have OLS method for calculating p_value

In [ ]:
from statsmodels.api import OLS
ols=OLS(y_train,x_train).fit().summary()
ols

- Based on alpha=0.05, we reject 3 columns : Fixed acidity,citric acid, residual sugar
- Again we need to build the model by using remaining features.

**Method 2: Correlation b/w the features.**

In [ ]:
cols=["fixed acidity","citric acid","residual sugar"]
new_data=df.drop(cols,axis=1)
new_data

In [ ]:
cor=new_data.corr()
cor

In [ ]:
import seaborn as sns
plt.figure(figsize=(10,8))
sns.heatmap(cor,annot=True)

- from above correlation, total sulpphur dioxide and free sulphur dioxide are highly positively related ie., 0.667
- we can only use any one of the column

In [ ]:
#check the relation 
new_data.columns
col1=new_data['free sulfur dioxide']
col2=new_data['total sulfur dioxide']
plt.scatter(col1,col2)

**Method 3: Variance Threshold method**

- Sometimes the column values doesnoot vary much. THEN WE CAN REMOVE THOSE COLUMN.
- for eg; in Loan prediction: loan term 360 column
- Every data has some variance. 
- Based on variance, we can decide the data is either constant or varying.
- if variance is 0, the data is not varying. By default python will drop such features/columns threshold =0.
- Variance threshold is Hyper parameter. We can choose threshold as any value say 0.1,0.2 0.3 etc..
- Based on internal team discussion, we will drop those feature which are having <= threshold value.
- most of the time, data has only one variance.
- it is vailable in sklearn.feature selection.

**p-value**
- H0: There is no r/n b/w x and y
- H1: There is r/n b/w x and y
- If p<0.05 - Reject the Null Hypothesis
- If p>0.05 - Not Reject the Null Hypothesis ie., does not Include the  observations

**Mutual Info classify**
- KNN and Entropy
- It will give the r/n b/w ip and op and will pick those which have more r/n
- ip vs op
    - 1) Entropy
    - 2) KNN
    - 3) R-square: explainability about y based on x

**Forward selection and backward selection**
-check article link in class file.
- https://courses.lumenlearning.com/introstats1/chapter/model-selection/#:~:text=The%20forward%20selection%20strategy%20is,measured%20by%20adjusted%20R2).

- **Forward selection method**
    - Start with epmty set of features and start adding one feature at a time.
    - Iterate through feature and select one feature that improves the model performance
    - Continue adding features one by one until we meet the criteria.
- **Backward selection method**
    - Start with full set of features
    - Iterate through each feature and  by removing the feature which is having less impact on the model.
    - Continue the process, till the performance is stable
- Both these methods are complex in nature. They take more time. hence many will avoid these methods in general.

**Vaeiance inflation factor (VIF)**
- VIF will give the analysis of multicollinearity.
- In VIF we find R-square value of each input feature w.r.t to other input feature.
- We will keep one feature as ip and other features are considered as op in Regression equation.
- This will keep on iterating through all features.
- Every feature behaves as both ip and op.
- As we know every regression line give Rsquare value from that value will fine VIF.
- we will drop the features having VIF>5 or VIF>!) based on internal team discussion.

-     check the image link in class notes  file.

In [ ]:
#Method 1 Variance Threshold method
import pandas as pd
dict1={'A':[100,200,300,400],
      'B': [1,2,3,4],
      'C': [10,20,30,40],
      'D': [10,10,10,10]}
df=pd.DataFrame(dict1)
df

In [ ]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
vt.fit(df)

In [ ]:
vt.variances_

In [ ]:
#300 is first column variance(True)
#1.25 is second col variance(True)
#30. is third col variance(True)
# 0 is 4th col variance(False) drop this col

In [ ]:
vt.get_support()

In [ ]:
vt.get_params() #gives hyper parameter we provided in the function

In [ ]:
cols=vt.get_feature_names_out()
#we include only these features 
df[cols]

In [ ]:
#apply all the above steps on Wine dataset
df1=pd.read_csv(file_loc)

In [ ]:
#keep thethreshold :0
#get the new data
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
#make sure before fitting the dataframe, drop the output column
x=df1.drop("quality",axis=1)
vt.fit(x)
cols1=vt.get_feature_names_out()
x[cols1]

In [ ]:
df2=pd.read_csv(file_loc)

In [ ]:
#keep thethreshold :0.1
#get the new data
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
#make sure before fitting the dataframe, drop the output column
x1=df1.drop("quality",axis=1)
vt.fit(x1)
cols1=vt.get_feature_names_out()
x1[cols1]

**Method 2 - Information Gain**
- Mutual info classify

In [ ]:
df3=pd.read_csv(file_loc)
x2=df3.drop("quality",axis=1)
y=df3["quality"]

In [ ]:
from sklearn.feature_selection import mutual_info_classif
MI=mutual_info_classif(x2,y)
MI

In [ ]:
np.sum(MI)

In [ ]:
#Series
val=pd.Series(MI)
val

In [ ]:
#Dataframe
d=pd.DataFrame(MI, columns=['Information Gain'],index=x.columns)
d

In [ ]:
#sorting
d.sort_values('Information Gain',ascending = False)

**Select K best**
- similar to Mutual info classify
- but we provide only necessary number of observations only in this method.

In [ ]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
df4=pd.read_csv(file_loc)
x3=df4.drop("quality",axis=1)
y2=df4["quality"]

top_5 = SelectKBest(mutual_info_classif,k=5)
val = top_5.fit(x3,y2)

**Pickling the Model (Share and use the model)**
- Handover the model to some other
- After Model is developed, we need to save the model inorder to handover it to anyone to use.

- we can save model in different formats:
    - pickle   .pkl
    - joblib   .joblib
    - save(in deep learning)

In [109]:
#saving the model as file
import pickle
pickle.dump(LR,open('linear_wine_model.pkl','wb'))
# wb -> write in bytes.

In [111]:
#loading the model from a file
model=pickle.load(open('linear_wine_model.pkl','rb'))
model

LinearRegression()

In [112]:
x_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
688,7.7,0.660,0.04,1.6,0.039,4.0,9.0,0.99620,3.40,0.47,9.4
961,7.1,0.560,0.14,1.6,0.078,7.0,18.0,0.99592,3.27,0.62,9.3
726,8.1,0.720,0.09,2.8,0.084,18.0,49.0,0.99940,3.43,0.72,11.1
537,8.1,0.825,0.24,2.1,0.084,5.0,13.0,0.99720,3.37,0.77,10.7
1544,8.4,0.370,0.43,2.3,0.063,12.0,19.0,0.99550,3.17,0.81,11.2
...,...,...,...,...,...,...,...,...,...,...,...
1461,6.2,0.785,0.00,2.1,0.060,6.0,13.0,0.99664,3.59,0.61,10.0
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6
1045,6.9,0.440,0.00,1.4,0.070,32.0,38.0,0.99438,3.32,0.58,11.4
1498,6.6,0.895,0.04,2.3,0.068,7.0,13.0,0.99582,3.53,0.58,10.8
42,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5

In [113]:
model.predict(x_test)

array([5.15272674, 5.32546327, 5.63662519, 5.51245819, 6.35588496,
       5.39028618, 5.37580837, 5.94379165, 5.49446987, 6.98211458,
       4.92847919, 5.18177228, 5.73271386, 5.56085417, 5.53985028,
       5.25272042, 4.93424659, 5.12423646, 6.27626835, 5.12589226,
       5.06691612, 5.91039778, 5.1797551 , 5.45854364, 5.72531378,
       6.31002431, 5.30913419, 5.50678991, 6.04808131, 5.47609822,
       4.72291628, 6.20818055, 5.21920961, 5.62421184, 5.55062526,
       5.52259916, 6.36735043, 5.23288886, 5.49938736, 5.80792898,
       5.16587916, 6.13318292, 5.72636822, 5.33537114, 5.63701918,
       4.96463531, 4.88029661, 5.78938553, 6.36333952, 5.56149953,
       4.95005899, 5.75085354, 6.67236186, 6.16951277, 5.34056761,
       5.12096361, 6.19641543, 5.21584694, 6.46449078, 5.25590493,
       5.27667097, 5.17871421, 5.09122333, 5.63083824, 5.01946398,
       6.16336001, 5.7427919 , 6.337122  , 5.28732968, 6.05063646,
       5.7342916 , 5.57340483, 5.21043842, 6.18633591, 5.50678991,
       5.3453067 , 5.99997768, 6.51564794, 4.85375662, 5.04018732,
       5.72499592, 5.59626211, 5.73949584, 5.95489086, 5.34697269,
       4.99839179, 6.13681154, 5.32302661, 6.01068016, 6.12678637,
       6.52768314, 5.39538409, 5.9974906 , 4.99004327, 5.44790697,
       5.86843828, 5.26806983, 6.65075932, 6.61072464, 5.99997768,
       5.37579844, 5.48785095, 4.94241599, 5.53013394, 5.51054593,
       5.25914217, 5.89858025, 5.16978949, 5.40527552, 5.44913755,
       6.38388834, 5.54138872, 6.22755065, 5.35050741, 5.55565805,
       5.69996464, 5.35611312, 5.91795566, 6.84295266, 5.21736143,
       5.93685756, 6.02728227, 5.65516136, 6.33585096, 6.11727608,
       5.10631555, 5.21930664, 6.51527783, 6.29685541, 6.23764222,
       5.2792288 , 5.03871695, 5.88172061, 5.0851889 , 5.27738598,
       6.35828943, 5.89939941, 5.45905811, 5.41928796, 5.57217489,
       5.93356169, 4.83777751, 5.43045252, 5.14580263, 5.75145727,
       5.77227893, 5.20511824, 6.22744476, 6.15111159, 5.37199058,
       5.43837324, 5.77768114, 6.61866538, 6.74493635, 5.99429439,
       5.77421449, 5.71445701, 5.63158268, 6.53617359, 5.61226567,
       6.41524291, 5.85713158, 6.03657959, 5.36589905, 5.79504901,
       6.15045308, 5.34746564, 4.18492552, 5.78179004, 5.9409628 ,
       4.87152252, 5.75689927, 4.97026015, 5.74576868, 6.55745611,
       6.04292031, 5.32973134, 5.52682185, 5.71987688, 4.93131525,
       6.04719996, 5.20606774, 5.85001588, 6.56279324, 5.22784496,
       5.13583528, 6.49406669, 6.67080913, 5.86790849, 6.22543582,
       5.99898464, 5.48676406, 4.68758173, 6.42891816, 5.3780084 ,
       4.72596428, 5.35624776, 6.98166918, 5.30720706, 5.01009976,
       5.9095069 , 5.89788367, 5.74541352, 4.97661924, 6.64061995,
       5.56824532, 5.88970167, 5.10254921, 5.03266072, 4.78859962,
       5.66137988, 5.01756041, 5.70331509, 5.08378929, 5.91679978,
       6.69986908, 5.31928286, 5.34669749, 5.31734828, 5.6188404 ,
       5.6103356 , 5.88657821, 4.82255134, 5.47617034, 5.82141836,
       4.96924459, 5.45555462, 6.15466593, 5.60961275, 5.97937907,
       6.29141847, 5.49532602, 5.7427919 , 5.02129556, 5.42567123,
       5.30376592, 6.44506134, 5.79457654, 5.85840874, 6.40681931,
       5.23356207, 5.09446531, 6.29040996, 5.23133575, 5.20440993,
       4.91613205, 4.85264526, 5.77402591, 6.44998907, 6.27228383,
       5.66752455, 5.77214065, 6.2457379 , 5.01756041, 5.88530413,
       5.46922842, 5.31254547, 5.16197206, 5.84930403, 5.45790288,
       5.45284814, 5.0309555 , 6.11126538, 6.39353084, 5.95035988,
       6.16294412, 6.11799254, 5.859645  , 5.32664826, 5.34056761,
       5.06423962, 5.32051406, 5.43624309, 5.33971951, 5.58178758,
       5.75588456, 6.04024883, 4.91167335, 5.60170434, 5.32877713,
       6.22983414, 5.89614721, 5.93360527, 5.39888101, 5.2739361 ,
       5.73794177, 5.86555862, 5.03944697, 5.32346217, 5.74101128,
       6.40284138, 5.96305686, 4.93108229, 5.90456997, 5.71279268,
       5.61244954, 5.14567686, 5.36421345, 4.96924459, 5.38200614,
       5.93259413, 6.61817345, 5.9401426 , 5.09222651, 6.59461735,
       6.37818219, 5.76677648, 5.00550284, 5.6642651 , 5.09132685,
       5.35617409, 5.0856266 , 5.76205873, 5.58353651, 6.11360811,
       5.26670428, 5.1502229 , 6.35872853, 5.78881572, 5.12077223,
       6.20379015, 5.12846456, 5.245733  , 5.62421184, 5.33216794,
       4.63391647, 6.67080913, 5.30197384, 6.07737771, 5.08945872,
       6.3404451 , 5.00101501, 5.76082175, 4.78681399, 5.43540031,
       5.5933712 , 5.20854044, 5.53965055, 5.51286652, 6.09119691,
       6.89645836, 6.5818963 , 6.51616813, 6.7389971 , 5.13583528,
       5.04542379, 5.55565805, 5.81421595, 5.8596704 , 5.5371316 ,
       5.52159867, 6.08766214, 5.33673345, 5.21641764, 5.5881843 ,
       4.83649958, 6.54755782, 6.15975664, 5.18758997, 5.543044  ,
       6.37948308, 5.27430664, 5.41978692, 5.95011166, 6.15443962,
       5.43156985, 5.17851884, 5.71776488, 5.31049826, 6.29287608,
       5.16405155, 5.51987093, 5.94985843, 5.45261618, 6.1957446 ,
       6.22450256, 6.34398536, 5.02138294, 5.08230935, 5.63470779,
       5.75689927, 5.56268525, 4.61066841, 5.6356401 , 5.91613694,
       4.96621268, 5.10918278, 5.66306872, 4.79517341, 5.79608951,
       6.11360811, 6.23317938, 5.15817553, 5.66531897, 5.37580837,
       5.25189877, 6.5720807 , 5.24409385, 5.55140543, 6.45336013,
       6.40942246, 4.83234267, 5.30326782, 4.96473992, 7.52775146,
       5.42951778, 6.38524949, 6.37419061, 6.63801798, 6.05922706,
       5.73767049, 6.03642831, 4.83223993, 6.24020332, 5.72479784,
       5.18607442, 5.05450429, 5.11697949, 5.13412713, 5.52440323,
       5.64867525, 4.98224538, 6.09363224, 5.44051117, 5.81230694,
       5.46789186, 4.55788622, 6.4346495 , 6.83493526, 5.55577486,
       5.78380845, 6.26550268, 5.16451239, 5.64312174, 5.19935697,
       6.36699511, 4.96641745, 5.86934155, 5.76462945, 6.36547688,
       5.57273104, 5.67822167, 5.3098559 , 5.32346217, 5.80379403,
       5.05273644, 4.89716249, 4.94106077, 4.39448333, 5.35399193,
       5.95011166, 5.47056853, 5.09916641, 6.15419278, 5.32886401,
       5.55946617, 6.39503255, 5.51496826, 5.09226489, 5.98738087,
       6.16951277, 5.66535961, 4.85264526, 5.32570564, 6.08694216,
       5.71886682, 6.18670867, 5.16933689, 5.47617034, 5.1985077 ,
       5.37466118, 5.4969461 , 5.11061722, 5.07457111, 6.43458746,
       5.16307079, 5.55639097, 6.16741756, 5.27142375, 5.67409146])

In [ ]:
#try loading the model and predicting using available data in separate notebook.